### ISSUE TITLE
maths equations not working

### ISSUE THREAD

**Issue by porjo** [RabbitHols/blazemark#1]
Looks great! I noticed maths equations not working. I've only tested using Firefox 95.0.2 on Linux

![Screenshot from 2022-01-05 07-46-31](https://user-images.githubusercontent.com/1296987/148128186-8461cdcf-986b-4fa2-80a1-60e88d6a6981.png)

It'd be great to know if you have any plans for more features - could you create a roadmap issue?

**Comment by RabbitHols** [comment]
> Looks great! I noticed maths equations not working. I've only tested using Firefox 95.0.2 on Linux
> 
> ![Screenshot from 2022-01-05 07-46-31](https://user-images.githubusercontent.com/1296987/148128186-8461cdcf-986b-4fa2-80a1-60e88d6a6981.png)
> 
> It'd be great to know if you have any plans for more features - could you create a roadmap issue?

No roadmap issue for now, it's just a project that I'm working for fun.
Math equations are not working because are not part of common mark specification.
